spring.application.name=foodiesapi
server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/foodiesdb

jwt.secret.key=${JWT_SECRET}

razorpay.key.id=rzp_test_XXXXXXXXXX
razorpay.key.secret=YOUR_RAZORPAY_SECRET_HERE

aws.access.key=YOUR_AWS_ACCESS_KEY
aws.secret.key=YOUR_AWS_SECRET_KEY
aws.region=ap-south-1
aws.s3.bucketname=your-bucket-name

logging.level.org.springframework.security=DEBUG

app.stub.payment=true
app.stub.storage=true